# Generated by Django 3.1.2 on 2020-11-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('cl', 'cl'), ('l', 'l'), ('g', 'g'), ('kg', 'kg'), ('tsp.', 'tsp.'), ('tbsp.', 'tbsp.'), ('pinch', 'pinch')], default='', max_length=50, verbose_name='Unit'),
        ),
    ]
