# Generated by Django 3.1.2 on 2020-11-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_nullable_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('cl', 'cl'), ('l', 'l'), ('g', 'g'), ('kg', 'kg'), ('tsp.', 'tsp.'), ('tbsp.', 'tbsp.'), ('pinch', 'pinch')], default='', max_length=50, null=True, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='portions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Portions'),
        ),
    ]
