# Generated by Django 3.1.2 on 2020-11-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20201128_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('cl', 'cl'), ('l', 'l'), ('g', 'g'), ('kg', 'kg'), ('ts', 'tsp.'), ('tbsp', 'tbsp.'), ('pinch', 'pinch')], default='', max_length=50, null=True, verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dish',
            field=models.CharField(choices=[('starter', 'Starter'), ('main_course', 'Main course'), ('dessert', 'Dessert')], default='main_course', max_length=50, verbose_name='dish'),
        ),
    ]
