# Generated by Django 3.1.2 on 2020-12-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_ingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='popularity',
            field=models.PositiveIntegerField(default=0, verbose_name='popularity'),
        ),
    ]
